language: go
jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - docker build -t telefonicainnovationalpha-health-docker.jfrog.io/franmrl-pipe-test
      .
    - docker push telefonicainnovationalpha-health-docker.jfrog.io/franmrl-pipe-test
  - stage: deploy
env:
  global:
  - secure: Y9Mo2BY8FpAq6OiOLQf9jNOfT09FIDRw4oz5tN9PBG64R3mG7lmZnE+F2/CRDK6RtbpzexFNre/5ZyDPtWkd5dil8SS6+4bCSwmyXaiB8e0AFtv/ed4CjEiDfguTfocEKcjm1aTJpcYZquycc1z4pBZz7jxg6bKBZ9sBCOd8i2NLkmg41GGZeZpXr9MMuyl7idbG+Q+JNwtEW+SZ2VerKCm7Zl4Q03nldRZ7R9tVJqtuHjL5YBFGynaDu1Qhz+nn4NZFYBeVCLTi8+Vl5NcF8SMRJH9twiiegLbDztS8XhT7sYAvteSD+Xe44H5I2iwvKP6pThAPXyFYW4/rcwnxijQyvD5ZnAjCYN1mYVn2yhvP9CUSZiW4TotLihV0fyaeV7tnnjE5lzBKrf8tthm05e1x0+tuDbVDWLmVFBBWjRqmT9v6gNmlx/BpYmTH3RiIDQBNsK+o58vNqP0KYHzoIs9R2w6QRNRJekyJy3oRKpljMtEpnMbBC+puLrpZMpt1PJsrDIImr+kh/zsKy2FF2JiShFQph7ZEmA/c9ztuhi6SLQTirPyTAcPFor9p8aSLKo+vUoMsGLnqlJpnW/yIP5+6rfCy3JQcWOO4FfoWUn2Yzqvo/wVdkcrKe3c9hEWiXgvj1rD23luUedngzLrlzkfh8EdL9or4gGs3bROZQnE=
  - secure: QqSVUjywOpp3Dx+nbt6EpdGyKczoiXXgPeteB/45tbF1cy+39wVUfo8ozVHPHjsnc2i3jQBpVNzv/Zxk2fMla61GDMmd2cY4FLoPUAaWXPJMnTgmgEWeuPOF1zhVg1pRFGvk3dLrBWdYXsXGx/J416UBoH+jQEjbUMfEUZ1QcVog569RbMv75zX2ZtNhOG4KH6HQO7YpB+6EfH5ASlgtv4otLy1ZGzqSz7PxmO84uSNxx1Naj6i9hEqZ0oUwpx1x/TnQu31CBUiKeEoZo7UFDc2JXjBa9e/HeyW8kmmcbhx32Tg4o1He30C0zra3x27Nki5R8t9jgom7avY4S99hXbGOits5rcWYQTMosT2gnOJOUq5sPRpBZK8a6ldAwRdtCWpHdZ+ZQmGIAs7pstkMbKOJICxqa0YNGE/sAmiAjhbCCtBEiLitwa6/D3pJAS1mflO0ShT2TZDMt5KKkvoJhNytVL5FbHFYU97onmLRJ4obZACDJtvp+vF0fEBhgxSNmhv7BOsL2gQ3UY55d503UsLR1VqPp+vzG3UlDgw5VLZ59KrLOOfr+yfLD0nsDsH2qg9yKozN9rYNJV4o3jqjAqhHukZRsO7zayfQW+ppj5q5dgfU9PHZSpfamCn+7IoXKCBcnx8rvNTtnexFCydU3jKjnTADqLoKVTiFJ+AbFmM=
