language: go
jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - docker build -t telefonicainnovationalpha-health-docker.jfrog.io/franmrl-pipe-test
      .
    - docker push telefonicainnovationalpha-health-docker.jfrog.io/franmrl-pipe-test
    - echo "$WHATEVER"
  - stage: deploy
env:
  global:
  - secure: Y9ODFfX4KL1VpRQSXO0ios8rQiEs5/lOcwkf5NAotDaWqYY1mzGX591kXLR3xr+o8flJOcMKi6I9rEgqvBiym+RY0DXoN60YJnp88P2RBa4kWHgVqDQFxyc9LWjX40BTWgZi6OI5N02Rd55OdCTB744H8wGIM85Z7TRCDCrZ9y0mRb7OqRh/BAiwfkTXgHfDRpKSSIe5E134YrFqlk9FbBspWPkeMkhc7mJalp6BeWoaoC+9Lq3RqcCHEKZwXWVWdaxtP52M6Eysmr+ij71JNwocbmMoVKrwkDPU4/chJn/H3YX5txoBVUwyN+RxYAlGnABJupgXHSXwiUIQ+Z1KRY1QQtrqM+PHkBWaJGD5ApZZaYW/JlWXcbQ+41Fs2QfIaAw6l7OMeOH/YbXsWtgM4PgmBKy9wxraoPW4k9XogY2LbqrxA5hANa/DwH/sVyn8KYhLn6Avg3ATcAHnf2v/mLxhkypchLMDGvIcjoUBx3IVP5KdmbZgmG/ScBA8CaON0qZtpJMGLOa97LdqgGK1dEzadLpB3Knte2qmvszxGlFNUnXILKXn/rN1vQIo9Ah6CJu3rgBUX2qQ3eTzshROuuYgopiYaRLnV31ymHOWvvh397ats0N+H7oyrqu0fNaZqLQPxzhg2HhCUQdikpsxaZU2xkRqF648wlnq6SJfxkI=
  - secure: EFQhGfS6tznXmQrWJfoWVOg1AhUqV7WwR9fRNchHc55ZelRHRwmzXWyWuB0BYqS2ZNnFmxTPzms6IGgRFCxhjGtqFoLFIToFUZl8r8/3EXUmy1tuF/cq6Ka62/8Taami3RS8YYyiL1Ln8CAIRe7o2IVcA1Zx67EdIY/y1C9dxPY1ZmRltDH/Vx0VtS93MhyrO8idTWZP4SlknDEqgNjDG+P6pGtz0k+7X3F7EFdn7Zm3L4zQiCyaHrTLWeKklN6ow/haRNSLgsJeMMw/tY33iEWU63PD5OHfY56qlWwr/SN84mSGPGu+bY49tUac6tPMnIbmO/p7v1TTMqTn1Ze58Mb6B/3OKiDp3KdhQsOaLpWSNpp8JJb8sFvZpb5nOfsf3PpIIP3r0/1qFiDg2S9o7YR4mlbkHgLHGYBzybG3WfAilc5qA1ZKoaErWGpavNvsHA7phckCaRUJyM3dX4CydmxiZ3hrfVwdxtvrSY6lABS6sVoWCy4uNVTKD7Txi93HmQW5d9AG/+RifyG5P/H5tW5cifhjQN5iljPOwkScQQVJR5/nEdo2yCSO2cXEVXMFywriGBR2VqJhskxmOCuTfMTZfkUYLV+OWtwTVYY+lg3rdBcei3hlzUQD7ffjnnitQNaShdOhxPlfzR31hrwey/Q2FrTFK3dkVGwpgq/YqLM=
