language: go
jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - docker build -t telefonicainnovationalpha-health-docker.jfrog.io/franmrl-pipe-test
      .
    - docker push telefonicainnovationalpha-health-docker.jfrog.io/franmrl-pipe-test
  - stage: deploy
env:
  global:
  - secure: NuPBbIZemhPgUKHrfPWibexAZP2dx1A0CCFlj1msPiE/kaT0oqphJsPp7mib/axQmmmLIqioTcq08ntaAssOPdgj7Hw/cp80hpy1N8GAAwH/uvTksj0RPACRlGnf1EHnz+aWLyHhynKoV5j3JnMUCpccLFVvAAl9Bkt+2h/hvpM4dSWkl8CPXgSoymMfldO8qRkQwo+D1J8Nv/3eJ0YcdJExZDFQyem5kFuL3SF3v1eUCw5X7iQpJ41Hm80HV1b2/jKkl25W8i0RhTB1WR3ERRaRK5iaGhzslCmpPyOVzaTcBpcJVtYh0HmXtK0/VzcIN8vr83pNvuJ3UQR/3wDjgLJgWJSSP1dC2fOjuv/N8IB7u7VkGXL+Y5zLQephmIozqMPVezZWDZlfp+LgkIGWA/6E7TQX021I5bK5EqLkn7R9EWxgzpW699qWFzE1tc7M2qLhfdkbL+sn9S1nzvdntXxk8w98EfQTRpGBh66rY9TYM86afbRZH9bm7VshosFsXX2UD7Sjid/gt3uq7W7nggfJFhM9hyi+1Mr/6GVQGASsEgAq3/sSN8pxYVb5vhRNXlGk9HJR0HXcmY6/qbDqkjVGkLAurwtdLEl1iFh21ApHgtJ1GM8bnoxMOvNVipQ6yU8F9EWJLOJpLErH0b2HggbBGiC1XdeFwg9KtK0inP8=
  - secure: uEg0IX/rGmB2iaipIyV9e6c/F/p4pGsnMyETdmpJkGkgHPzvpHfbf4vlp/9PKqNERzYbuS3i0I/Ve9h192LVksbfXWNLrrM1YB4utc4awcbM2adDUS9wXl+9Wqn5I7+6G8z5JH11BJw3VU8iDO58z7Qyy4RIo9XzEBoipcATRBI1BcTgD7vvqTRWAahjUJhcvofYqRBD3/Q70x9Ad+ggVKmO1Fu5i+jvI0J2gjh5DRsJJ5K81A/jXow7wqG1xgGrXqXnkxQXNSDjVnmM7IVQIK07kJvkoRRS+TzPDc9zy+dN7f7p/9jijF9iOQ338/TuRFDOQvpYKNSwVQ++KYkoDiKiPTy+mb4dTiVZDUE2oukBXyHJ3tIXA9Zb2jAaQpdbn/hB4x0/BRhsZdigVzkfC6HcZ7IaCvhr5HMg6w37yG+knHos2Y7gnj4/xWnmwobhVlEp5c6GRRr7aIni6HrI35JMoNePVuqoHBzOYUZXPCvyqANyGt1fYp7R+amiFciYOhEF50V3vGqiyRIhHg40ZxEsPZRlyq5KwJXdcvpiuRlkfl6nWdDBFZZI7qQ7w8NRDOJbmQP/A+o+ErYZwsB//9Hti/n9nQv7jGZ3o90z+200RRfPq1njerdxVGeR88mLzM1Dt5LyqCu7IpYeWo5nNavNRewPFiqzOp5GyXdWu9g=
