language: go
jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - docker build -t telefonicainnovationalpha-health-docker.jfrog.io/franmrl-pipe-test
      .
    - docker push telefonicainnovationalpha-health-docker.jfrog.io/franmrl-pipe-test
    - echo "$WHATEVER"
  - stage: deploy
