language: go
jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - docker build -t telefonicainnovationalpha-health-docker.jfrog.io/franmrl-pipe-test
      .
    - docker push telefonicainnovationalpha-health-docker.jfrog.io/franmrl-pipe-test
  - stage: deploy
env:
  global:
  - secure: mwF6FhDHDzGTDZeT3XB77VuOigqFsU7MTcZXf5ZKVFcvTm/v+P/CTUAqXODxcAEtPINGjA4gyCRRcH4t5A/SEX0xmtM9C+GXQQA+1o735v3GlyIjmXo8DTxoAKLtgk2V9syA4Hx4ta0XkjUiaE0dadotUI/Z9xaNwHt8PRz9hh3QxUlRESJyHb8kBFPX0pqOPOBA7NCwsXymb5bQzrWqnNWssso9FkAko4RvdUaR/H7cpwtx1A2V0UUQjAucQIkr3EvB/sY4d7GsfmivQ5BT2sGKSmR8+YsPgis1wSbZHQLiuJsb/GVN+2ZqUD3heEnDZG/3WQjDXZmuiC/CmbnnkPUcFdfXBc4gKs/wfZgJr9Y6fs2vAYckPaX+IupU6afWUH7HSzb0CDWs2x1uOrDfnYbVIjE0kWyMzD7oft3p7UUFP4rhlrUSvD4asL0LUHavuYc6U3O0MZEywFT+iz6XInvkoT4fwwdW+fnu2Wh9OXUqEP7lBV3QrDdWPqvVCBIRxz6/dmszT6QaQuHYrVzSA5Z1CErVXNDnOmNH9NaMFxJ7AuG5O0GkXN9DVfANNdg2WThDIE5xOdO5Salvi28Hui939lyyKL9hI6qByK4+t4Qa0YsR8B4MFxove+8Ezq+gD4z9fzZ7ZJDTPbHq0BqVxY/GDZksz+2yp0VuSnJmpMw=
  - secure: JlODXYPpDwR/YogluZybRIclh22TTeRtnb02sCgwV1gnm3qaNrPKuG+xXRWfJYUYLLpu1w9CoTnDVuwpr6UX+KiIlkO9VykWbR1C4CyW9tXCKfK2Hgro71dDK3F6Fb79I2dfWcffM4c94shCe4bN2AS4F9cwmbRY2GnO7WP9EoFWJSHtJ3ng2iO63NPdySHnT13vg2N4tYJiHMZ0BjvS5n3dlcOvQFphYH9YUmKV9sjvAvV5jQMkbX1zwiOIgizZhEw4/tVSK5xSs9auM9jnRWCFTuHz2Aqx61frN4fdjbw7RZCMujQS5Th36tPcELunrbTlW5WKRjNkzu9vQO7XPOZvcQy3vCdOuUY0gv6r4cSfYaOVAVS9vFTNEAL1WIHwbntkGn0agTKi1sGdLzin8FUJ55uH5kkrYnsvLEghbFk7ZUHQiKCCCjvirOy/xIwyYEmW5YcuXBb7OK7H/4JT05NBsQBms4sLkXrhpogAuE4WzcWkyD/HxmK/5suMv0nA0Z9VeQDwwQ+jYVnM7nAyt0E9GNJCs2kHDe1wjiyzOw49ktxRtpB3ughAk5owUpDVR8MuNiUinqpLr2yN5X91Nzki4uRkg1WyipCS19a5ux2cvUXqhPM/i1zICjtUA2f/q2WEaGXDMv/mxY0vefpeaBIjImIqXaI7S6spaalCnrk=
