language: go
jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - docker build -t telefonicainnovationalpha-health-docker.jfrog.io/franmrl-pipe-test
      .
    - docker push telefonicainnovationalpha-health-docker.jfrog.io/franmrl-pipe-test
  - stage: deploy
env:
  global:
  - secure: jkENonROqaTGkHpofBYKcfsfLsSdo3D7sWTycdMm6Ry9BuLWUJbr+4PF0tZ6WaefA9sMj3NqtQ/TfQkHFIIt7KRIeCmZGpkw/S6amv1hMZ2SR/HmTxFgoj69PZY0j/PpRJBX4ptjCQ6nv7FiSXaUX9Nbuu3Ku27QBMANh8v9DqIwr738z+VpBWRFfHkzftbaGRsDRDwUqGnImGIXhVAzdgHflhV9c9cbbeq2aUscI2cuZOmYBDQr5wMIxQLXnacm9DJk567ACSrn8xEUz7mg48ZHwKWqtVVVdJciBz5+Q1G7l6lYWycgF8IAzt2pwi4Rqko+lwuwV6jg/mHdNme2+MOLbo/QGziBfmHzh9OQvCWBH98s4yTjXHfMZ10AbG+Q3/7VcPyuoelypiAn6+gug8JotPOBGaV4ktYVSaTXtPh4U6iw5NYO7BbaKM0lg7IEu6WI1DUFPFalvXRtxX7xG+KuMZ3AiPP4wPVlh8bgEdOuNrvdaL6CQJfiqlAhK+HCYky6ElaJHxrkouM3G9bTaPtFeqHjVPY+sIEU19wQ1anvhKqi+1bni6FYaVJk6/wzCk3Kn3/teZIk6zGT83khI8cDTzsHqBqBYVaw/+ibWtEeaRE85M1f1wCNakeoj6S9eyXOUrGgyH3iZCY3JGtFujcNpUufmtHC0jzcaA9rZu4=
  - secure: iidhJVSauHBMOq7AkgmvKrSQEwnIKFxz+GdGdDfeG1h8KbMrCxuY10KvIo8S6YfcXVzV9TOAFYc7eAtcyqocDKNUEyeY0/Q/wLAmKY1PSf/RzaTLplgMgAwnyAR2jVqwvw1o569On+RB3P2x0bycq4BfoM/rkz/CX78t1OGasBZAzaJDnTppDdKOBzPM4DLR45Y7UT5UqCphY91pIwJ7BaZgUS2ow2r/yl2MxYDTCbC2Yp5LF7KRlHK0jzAIhxifx3phYgetHG/hfdUWWCXLa9iHa59Tat1kHISUr6M2QZQHrYerJkCqpemVO56Nnby12iwJT0Adla3uEndqco7ERROt/5h9ASBWr9VCjd/aDXS87ziX+h1BqN9LlbkHlZdyoFHGRhpXV/xw94s5QilLO4b8g+9C9x3joe5XOkTVuLMZJXrfeawcyqmLh8O2pKsohh5GbWWp1LLsU8Es6R9FUxIqYGWy8FLwPisl7+GvN85Eqypoz1sOc4zpDTLPW4hIaiNkraC7nIeluhUV62Y8ACDgWt0OaRMvNFFZKS0kSxw5wQO8RwGdpaIN7+LAeai7Ov6nCT8bPIayW3YhP8pTWZJmZubi5K0uU0mEe8WXtJvLdaCCN1Prv9Nzq5MWzyXjiOecVZljcni/V2zRRn8SribpNnAM7JO/h1gl1WUEtkE=
